global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'jenkins'
    metrics_path: /prometheus/
    static_configs:
      - targets: ['jenkins-blueocean:8080']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io
        - https://prometheus.io  
        - https://example.com 
        - https://siddhantprateek.tech
        - https://resto-steel.vercel.app
        - https://landate.siddhantprateek.tech
        - https://celuxe.vercel.app
        - https://greate-escape.fly.dev
        - https://opendesk.vercel.app
        - https://flintmoney.vercel.app
        - https://healthgenic.vercel.app
        - https://spacenest.vercel.app
        - https://netflux-1xg0mz0y0-siddhantprateek.vercel.app
        - https://filtered.vercel.app
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  
  - job_name: 'blackbox_exporter' 
    static_configs:
      - targets: ['blackbox:9115']